<?php
return array(
	'name' => 'Blog',
	'desc' => __('Please note that this element shows already created blog posts. To create one go to the Posts tab in the WordPress main navigation menu on the left - add new. You do not have to go to Settings - Reading to set the blog listing page.' , 'wpv'), 
	'icon' => array(
		'char' => WPV_Editor::get_icon('blog'),
		'size' => '30px',
		'lheight' => '45px',
		'family' => 'vamtam-editor-icomoon',
	),
	'value' => 'blog',
	'controls' => 'size name clone edit delete',
	'options' => array(
		array(
			'name' => __('Column Title', 'wpv') ,
			'desc' => __('The column title is placed just above the element.', 'wpv'),
			'id' => 'column_title',
			'default' => '',
			'type' => 'text'
		) ,
		array(
			'name' => __('Column Title Type', 'wpv') ,
			'id' => 'column_title_type',
			'default' => 'single',
			'type' => 'select',
			'options' => array(
				'single' => __('Type 1', 'wpv'),
				'double' => __('Type 2', 'wpv'),
				'no-divider' => __('No Divider', 'wpv'),
			),
		) ,
		array(
			'name' => __('Style', 'wpv') ,
			'id' => 'news',
			'default' => 'false',
			'type' => 'select',
			'options' => array(
				'false' => __('Big Images', 'wpv'),
				'true' => __('Small Images in Columns', 'wpv'),
			),
			'field_filter' => 'fbs',
		) ,
		array(
			'name' => __('Columns', 'wpv') ,
			'desc' => __('Number of posts to show per row.', 'wpv') ,
			'id' => 'column',
			'default' => 1,
			'min' => 1,
			'max' => 4,
			'type' => 'range',
			'class' => 'fbs fbs-true',
		) ,
		array(
			'name' => __('Count', 'wpv') ,
			'desc' => __('Number of posts to show per page.', 'wpv') ,
			'id' => 'count',
			'default' => 3,
			'min' => 1,
			'max' => 50,
			'type' => 'range',
			'class' => 'fbs fbs-false fbs-true',
		) ,
		array(
			'name' => __('Category (optional)', 'wpv') ,
			'id' => 'cat',
			'default' => array() ,
			'target' => 'cat',
			'type' => 'multiselect',
			'class' => 'fbs fbs-false fbs-true',
			'layout' => 'checkbox',
		) ,
		array(
			'name' => __('Posts (optional)', 'wpv') ,
			'desc' => __('If you select any posts here, this option will override the category option above.', 'wpv') ,
			'id' => 'posts',
			'default' => array() ,
			'target' => 'post',
			'type' => 'multiselect',
			'class' => 'fbs fbs-false fbs-true',
		) ,
		array(
			'name' => __('Image', 'wpv') ,
			'id' => 'image',
			'desc' => __('If the option is on, it will display Featured Image of blog post.', 'wpv') ,
			'default' => true,
			'type' => 'toggle',
			'class' => 'fbs fbs-false',
		) ,
		array(
			'name' => __('Image Height', 'wpv') ,
			'id' => 'image_height',
			'default' => 400,
			'min' => 0,
			'max' => 1200,
			'type' => 'range'
		) ,
		array(
			'name' => __('Display Post Content', 'wpv') ,
			'id' => 'show_content',
			'desc' => __('Type 1: If the option is on, it will display the content of the post, otherwise it will display the excerpt.<br>
				Type 2: If the option is on, the post excerpt will be shown, otherwise no content will be shown.', 'wpv') ,
			'default' => false,
			'type' => 'toggle',
			'class' => 'fbs fbs-true fbs-false',
		) ,
		array(
			'name' => __('Nopaging', 'wpv') ,
			'id' => 'nopaging',
			'desc' => __('If the option is on, it will disable pagination.', 'wpv') ,
			'default' => true,
			'type' => 'toggle',
			'class' => 'fbs fbs-false',
		) ,
	) ,
);
